GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type:application/json

{
    "title":"Always separate app and server files !",
    "author":"nermineslimane",
    "url":"https://dev.to/nermineslimane/always-separate-app-and-server-files--1nc7",
    "likes":4
}

###
POST http://localhost:3003/api/blogs HTTP/1.1
content-type:application/json

{
    "title": "Type wars",
    "author": "Robert C. Martin",
    "url": "http://blog.cleancoder.com/uncle-bob/2016/05/01/TypeWars.html",
    "likes": 2
}